// Generated by orbit-build. DO NOT EDIT.
export interface CommandMap {
  "memo.runtime": CommandDefinition;
}
export interface EventMap {
  [name: string]: unknown;
}
export interface CommandDefinition<Request = unknown, Response = unknown> { request: Request; response: Response; }
export interface InvokeOptions { timeout?: number; signal?: AbortSignal; }
export interface ListenOptions { signal?: AbortSignal; once?: boolean; }
export type Unlisten = () => void;
export interface OrbitEvent<T = unknown> { readonly name: string; readonly payload: T; readonly source: unknown; readonly target: unknown; }
export class OrbitIpcError extends Error { readonly code: string; readonly data: unknown; constructor(code: string, message: string, data?: unknown); }
export interface OrbitBridge {
  invoke?(command: string, payload?: unknown, options?: InvokeOptions): Promise<unknown>;
  listen?(name: string, handler: (event: OrbitEvent) => void): Unlisten;
}
export interface ClientOptions { bridge?: OrbitBridge; }
export type CommandArguments<T> = null extends T ? [payload?: T, options?: InvokeOptions] : [payload: T, options?: InvokeOptions];
export interface OrbitClient<C extends { [K in keyof C]: CommandDefinition }, E extends object> {
  invoke<K extends keyof C & string>(command: K, ...args: CommandArguments<C[K]["request"]>): Promise<C[K]["response"]>;
  readonly commands: { readonly [K in keyof C]: (...args: CommandArguments<C[K]["request"]>) => Promise<C[K]["response"]> };
  listen<K extends keyof E & string>(name: K, handler: (event: OrbitEvent<E[K]>) => void, options?: ListenOptions): Unlisten;
  once<K extends keyof E & string>(name: K, handler: (event: OrbitEvent<E[K]>) => void, options?: Omit<ListenOptions, "once">): Unlisten;
  isAvailable(): boolean;
  dispose(): void;
}
export function createClient<C extends { [K in keyof C]: K extends keyof CommandMap ? CommandDefinition : never } = CommandMap, E extends object = EventMap>(options?: ClientOptions): OrbitClient<C, E>;
export const configurationFingerprint: string;
export function invoke(command: string, payload?: unknown, options?: InvokeOptions): Promise<unknown>;
export const commands: OrbitClient<CommandMap, EventMap>["commands"];
export const listen: OrbitClient<CommandMap, EventMap>["listen"];
export const once: OrbitClient<CommandMap, EventMap>["once"];
export function isAvailable(): boolean;
